// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrivagoFinance.Ui.Data;

namespace TrivagoFinance.Ui.Migrations
{
    [DbContext(typeof(TrivagoDbContext))]
    [Migration("20190708204833_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrivagoFinance.Ui.Data.DomainModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AproveStatus");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhotoPath");

                    b.Property<int>("UserRole");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AproveStatus = false,
                            Email = "darkogele@hotmail.com",
                            FirstName = "Darko",
                            LastName = "Gelevski",
                            PasswordHash = "e823a44aca1edda7551208a4c1c1559f61d30a821862b311df3a76ab2b901bce",
                            PhotoPath = "bd323643-d2c5-4f80-8d7e-db27716d80b2_dareto.jpg",
                            UserRole = 1
                        },
                        new
                        {
                            Id = 2,
                            AproveStatus = false,
                            Email = "lead@trivago.com",
                            FirstName = "Lead",
                            LastName = "TeachLeadGuy",
                            PasswordHash = "645978287991a6f40bcaf5840f5653b89b75b3bd1ea78cf9f39192e2400ac23e",
                            UserRole = 2
                        },
                        new
                        {
                            Id = 3,
                            AproveStatus = false,
                            Email = "finance@trivago.com",
                            FirstName = "Finance",
                            LastName = "FinanceGuy",
                            PasswordHash = "b696d75511dc16f2b52563e3113a498311a79866f4672862197aa9a8c5c0da12",
                            UserRole = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
