// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrivagoFinance.Ui.Data;

namespace TrivagoFinance.Ui.Migrations
{
    [DbContext(typeof(TrivagoDbContext))]
    [Migration("20190710184921_changesToDb")]
    partial class changesToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrivagoFinance.Ui.Data.DomainModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AprovalStatus");

                    b.Property<int>("Department");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhotoPath");

                    b.Property<int>("UserRole");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AprovalStatus = 0,
                            Department = 9,
                            Email = "darkogele@hotmail.com",
                            FirstName = "Darko",
                            LastName = "Gelevski",
                            PasswordHash = "e823a44aca1edda7551208a4c1c1559f61d30a821862b311df3a76ab2b901bce",
                            PhotoPath = "895d0fe3-076c-4124-8eb9-ab5424175abb_24909662_10157239995384896_4609835183655791985_n.jpg",
                            UserRole = 1
                        },
                        new
                        {
                            Id = 2,
                            AprovalStatus = 0,
                            Department = 9,
                            Email = "lead@trivago.com",
                            FirstName = "Lead",
                            LastName = "TeachLeadGuy",
                            PasswordHash = "E3456BC1F4D270F4A97933758645FDC21E39642B31CA343C1818F7972AC27906",
                            UserRole = 2
                        },
                        new
                        {
                            Id = 3,
                            AprovalStatus = 0,
                            Department = 7,
                            Email = "finance@trivago.com",
                            FirstName = "Finance",
                            LastName = "FinanceGuy",
                            PasswordHash = "b696d75511dc16f2b52563e3113a498311a79866f4672862197aa9a8c5c0da12",
                            UserRole = 3
                        },
                        new
                        {
                            Id = 4,
                            AprovalStatus = 0,
                            Department = 9,
                            Email = "employee2@trivago.com",
                            FirstName = "John",
                            LastName = "Smith",
                            PasswordHash = "e823a44aca1edda7551208a4c1c1559f61d30a821862b311df3a76ab2b901bce",
                            PhotoPath = "b8aaa1a4-22fc-4b66-8f9f-a3da69a2de7a_travel_expense_report.png",
                            UserRole = 1
                        },
                        new
                        {
                            Id = 5,
                            AprovalStatus = 0,
                            Department = 9,
                            Email = "employee2@trivago.com",
                            FirstName = "Rebeka",
                            LastName = "Week",
                            PasswordHash = "e823a44aca1edda7551208a4c1c1559f61d30a821862b311df3a76ab2b901bce",
                            PhotoPath = "b8aaa1a4-22fc-4b66-8f9f-a3da69a2de7a_travel_expense_report.png",
                            UserRole = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
